apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api
    app.kubernetes.io/managed-by: Helm
  name: api
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.targetPort }}
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}