version: "3"
services:

  api:
    container_name: api
    build: api/.
    ports:
      - "5000:5000"
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: todo
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: your_mongodb_password
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/opt/app
    depends_on:
      - mongodb
 
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local