# Default values for api-helm-chart.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: talk2toks/flask-api
  tag: v0.0.2
  pullPolicy: IfNotPresent
service:
  name: flask-api
  externalPort: 80
  internalPort: 5000
  port: 5000
  targetPort: 5000
resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"