# Default values for api-helm-chart.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: talk2toks/flask-api
  tag: v0.0.8
  pullPolicy: Always
service:
  name: flask-api
  externalPort: 80
  internalPort: 5000
  port: 5000
  targetPort: 5000
resources:
  requests:
    memory: "64Mi"
    cpu: "512Mi"
  limits:
    memory: "128Mi"
    cpu: "1Gi"
mongodb:
  MONGODB_HOSTNAME: "mongodb"
  MONGODB_DATABASE: "todo"